services:
  api:
    build:
      context: ./kayak-weather-api/
    container_name: kayak-api
    environment:
      - TZ=America/Los_Angeles
    restart: always
    networks:
      - web_gateway

  frontend:
    build:
      context: ./kayak-weather/
    container_name: kayak-frontend
    depends_on:
      - api
    restart: always
    networks:
      - web_gateway

networks:
  web_gateway:
    external: true
